flowchart TD
    code2docs_cli["code2docs.cli<br/>10 funcs"]
    code2docs_config["code2docs.config<br/>2 funcs"]
    code2docs_formatters["code2docs.formatters<br/>18 funcs"]
    code2docs_generators["code2docs.generators<br/>67 funcs"]
    code2docs_sync["code2docs.sync<br/>10 funcs"]
    code2docs_cli -->|2| code2docs_config
    code2docs_generators -->|1| code2docs_formatters
    code2docs_cli -->|1| code2docs_sync
